version: "3"
services:
    web:
        environment:
            - API_KEY=fe280a95fb920174dd75e3066c7cc1b8
            - ENVIROMENT=prod
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/love-my-movies
        depends_on:
            - docker_redis
    docker_redis:
        image: redis